FROM registry.access.redhat.com/ubi8/ubi-minimal as nativebuilder

COPY utsuki-bot utsuki-bot
RUN chmod +x utsuki-bot

RUN mkdir -p /tmp/ssl \
&& cp /usr/lib64/libstdc++.so.6 /tmp/ssl/libstdc++.so.6 \
&& cp /usr/lib64/libgcc_s.so.1 /tmp/ssl/libgcc_s.so.1 \
&& cp /usr/lib64/libz.so.1 /tmp/ssl/libz.so.1

FROM gcr.io/distroless/base-debian12:latest-arm64
COPY --from=nativebuilder /utsuki-bot /utsuki-bot
COPY --from=nativebuilder /tmp/ssl/ /
ENV LD_LIBRARY_PATH /
CMD ["./utsuki-bot"]